In [ ]:
#Today concept:
#python Special Functions:
map()
filter()
reduce()
lambda

In [ ]:
#map() function
syntax : map(functionname, seqence)
    map(add,[1,2,3,4])

In [7]:
#example:
def addSum(x):
    return x+x
li = [2,3,4,5,5,5,3]
data = set(map(addSum,li))
print(data)


{8, 10, 4, 6}


In [ ]:
#Filter()
syntax:
    filter(funname,seq)
    


In [8]:
#example
def numFilter(x):
    if x>=5:
        return x
data = filter(numFilter,(2,3,5,6,8,11,1))
print(list(data))

[5, 6, 8, 11]


In [10]:
def stringFilter(s):
    if s==s[::-1]:
        return s
palins = filter(stringFilter,["mam","121","python","lol","525"])
print(list(palins))

['mam', '121', 'lol', '525']


In [ ]:
#Task :
vowels = ["a","e","i","o","u"]
seqence = ["s","u","r","y","a","p","y","t","h","o","n"] given by user
filter only vowels

In [12]:
def filtera(x):
    a=["a","e","i","o","u"]
    for i in a:
        if x in a:
            return x
p=filter(filtera,["s","u","r","y","a"])
print(list(p))

['u', 'a']


In [ ]:
#reduce:
syntax :
    reduce(add, [1,2,3,5,6,7])

In [14]:
#example:
import functools
#factorail of 3
def fact(x,y):
    return x*y
fact1 = functools.reduce(fact,range(1,4))
print("factorial of 3:",fact1)


factorial of 3: 6


In [ ]:
#lambda Function:
def func():
    syntax:
        
        lambda arguments: expression


In [16]:
#example:
def cube(x):
    return x*x*x

result =lambda y: y*y*y
print(cube(5))
print(result(8))

125
512


In [19]:
#map() function with lambda
tup =(5,6,9,45,90,34,12)
newtuple =map((lambda x:x%2==0),tup)
print(tuple(newtuple))

(False, True, False, False, True, True, True)


In [22]:
#filter with lambda
li = [34,78,99,3,7,9,56]
odd = filter((lambda x:x%2!=0),li)
print(list(odd))

[99, 3, 7, 9]


In [25]:
#Reduce with Lambda
import functools
li = [10,20,30,40,50,60]
serialsum = functools.reduce((lambda x,y: x+y),li)
print(serialsum)

210


In [30]:
#filter with map() and lambda:
result = map((lambda x: x+x),filter((lambda x:x>=5),[4,5,6,9,10,3]))
print(list(result))
            
              

[10, 12, 18, 20]


In [ ]:
li= [34,67,89,44,22,94,12,58]

In [52]:
evenSum = reduce(lambda x,y:x+y,filter(lambda x:x>=40,map
                                       (lambda x:x+x,li)))
evenSum

400

In [ ]:
#Data science concepts:
1. Numpy (Numerical + python)
2. pandas
3. Matplotlib


In [ ]:
#features
1. power N-dimensional array object
2  scientific computing
3. tools for integrating c/c++
4. linear algebra
5. ramdom numcial data

In [ ]:
#Numpy array?


In [55]:
#single dimensional array
import numpy as np
a = np.array([1,2,3])
a
#print(a)

array([1, 2, 3])

In [56]:
a = np.array(([3,5,6],[7,8,9]))
a #multi dimensional array

array([[3, 5, 6],
       [7, 8, 9]])

In [ ]:
#Numpy operations:
1. ndim
2. dtype
3. shape - number of rows and columns
4. itemsize- size of elements in the form of bytes
5. reshape - change the shape of created array
6. arange(low, high, size)
7. arthimatic operations (add,sub)
8. size  - number of elements in the array
9. zeros(3,4) ,ones(2,2)


In [74]:
a = np.array(([1,2,3],[5,6,8]))
print(a.ndim)
print(a.dtype)
print(a.shape)
print(a)
print(a.reshape(3,2))
print(a.itemsize)
print(a.size)

2
int32
(2, 3)
[[1 2 3]
 [5 6 8]]
[[1 2]
 [3 5]
 [6 8]]
4
6


In [75]:
a = np.arange(0,30,5)
a

array([ 0,  5, 10, 15, 20, 25])

In [77]:
a = np.arange(50)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [88]:
#accessing elements in numpy array
#slicing
a = np.array(([5,8,9],[11,56,90],[100,150,250]))
a
print(a[0:,2])
print(a[0,1])
print(a[0:3,2])

[  9  90 250]
8
[  9  90 250]


In [99]:
#arthimatic operations
a1 = np.array(([5,7,8],[7,8,9]))
a2 = np.array(([9,3,7],[6,9,4]))
print(a1)
print(a2)
#add, sub ,mul,div
print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)

[[5 7 8]
 [7 8 9]]
[[9 3 7]
 [6 9 4]]
[[14 10 15]
 [13 17 13]]
[[-4  4  1]
 [ 1 -1  5]]
[[45 21 56]
 [42 72 36]]
[[0.55555556 2.33333333 1.14285714]
 [1.16666667 0.88888889 2.25      ]]


In [108]:
#min,max,sum
a1 = np.array(([5,7,8],[7,8,9]))
a2 = np.array(([9,3,7],[6,9,4]))
print(a1)
print(a2)
print(a1.min())
print(a2.max())
print(a1.sum(axis=0))
print(a1.sum(axis=1))

[[5 7 8]
 [7 8 9]]
[[9 3 7]
 [6 9 4]]
5
9
[12 15 17]
[20 24]


In [118]:
#square root and standard deviation
print(np.sqrt(a1))
print(np.std(a1))


[[2.23606798 2.64575131 2.82842712]
 [2.64575131 2.82842712 3.        ]]
1.247219128924647


In [121]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [122]:
np.ones((2, 2), int)

array([[1, 1],
       [1, 1]])

In [124]:
np.zeros((3,3),float)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Pandas

    - Pandas is a python library used for data analysis which contains data structures for analysing the large data sets. The functions in pandas will help us to perform operations easily on data sets. 

 - Series
     - series is one dimensional data structure
 - Data Frame
     - two dimensional data structure

In [130]:
import pandas as pd
names = ["vijay", "sai", "ravi", "ramu", "pavan"]
s = pd.Series(names)
s

0    vijay
1      sai
2     ravi
3     ramu
4    pavan
dtype: object

In [132]:
s[2]

'ravi'